### ISSUE TITLE
[PE-D][Tester D] Delete command does not appropriately handle the case when the index is larger than java integer max value

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#112]
**Overview**
The error message displayed when the delete index is 2147483647 vs when it is 2147483648 is different.
At index 2147483647 it says 
> index provided is invalid

but at 2147483648 it says 
> command not found

It suggests that at `delete 2147483648` the value overflows and becomes negative, so the command registers it as a negative delete index, which consequently results in a different error message. 
 
**Steps to reproudce**
- Run HackLink as indicated in UG
- Type `delete 2147483647` and press Enter
- You will get the output: 
> The person index provided is invalid
- Now type `delete 2147483648`
- Yow will get a different output:
> Invalid command format! 

**Expected behaviour**
- Error saying ."The person index provided is invalid" in both cases.

**Actual behaviour**
- Invalid Command format error for  `delete 2147483648` which shouldn't be the case.

**Screenshots**

![image.png](https://raw.githubusercontent.com/ararchch/ped/main/files/e164360b-e2ea-41a6-bd40-879823c35d60.png)

![image.png](https://raw.githubusercontent.com/ararchch/ped/main/files/f4d8aafc-5ea9-431f-9971-6bdcef99cd5f.png)

**Potential solution**
I think this bug reflects the issues of handling the delete index as an integer, and it might be a good idea to change it so that index parameter accepts values up until one that is definitely unreachable (eg: more than the world's population).
If not possible to change the limit, I think it should be included as a known bug in the UG / in the delete error message constraints.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ararchch/ped#7

**Comment by julia-cp** [comment]
- descriptive title: :heavy_check_mark:
- enough details: :heavy_check_mark: 
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :heavy_check_mark:

Good report

**Comment by julia-cp** [comment]
can put this as known limitation in UG

**Comment by dhlee03** [comment]
Intentional sabotage using unrealistic index that would not be used in hackathon
