### ISSUE TITLE
[PE-D][Tester D] Undo and redo commands are implemented but are not listed in user guide command summary section

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#120]
**Overview**
Quite self explanatory as well, the undo and redo commands are not listed in the command summary in the UG.

**How to replicate**
- Scroll to the command summary section of the UG

**Expected Output**
- Undo and redo are present

**Actual output**
- undo and redo are missing

**Screenshots**

![image.png](https://raw.githubusercontent.com/ararchch/ped/main/files/cda7099e-e94f-4327-8476-c4b9966f44df.png)

**Potential solution**
Add the commands to the section - a very easy fix.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ararchch/ped#14

**Comment by bachletuankhai** [comment]
- descriptive title: :heavy_check_mark:
- enough details: :heavy_check_mark: 
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :heavy_check_mark:

Good report
