### ISSUE TITLE
[PE-D][Tester D] Logo of the product is still that of the addressbook 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-4/tp#127]
**Overview**
The logo that is displayed upon launching the product on my Windows laptop is still that of AB3. Might be beneficial to change it to something more unique and relevant to the product and its use case. This is a small fix that can really enhance the product and help users better appreciate its purpose. (Doesn’t fit well with the product)

**Steps to reproduce**
- Launch the product using the jar file as recommended
- View the task bar of your laptop and the top left corner of the window to see existing AB3 logo

**Expected outcome**
A unique logo that reflects that this is a hackathon management software.

**Actual outcome**
Generic AB3 logo that does not complement the use case and functionality of the product well.

**Potential solution**
Replacing the picture with a more appropriate one for HackLink would be great

![image.png](https://raw.githubusercontent.com/ararchch/ped/main/files/79f820ca-71f1-44e9-8010-253c0c59ea8d.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ararchch/ped#21

**Comment by bachletuankhai** [comment]
- descriptive title: :heavy_check_mark:
- enough details: :heavy_check_mark: 
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :x: (not exactly a problem, but the app icon is not much related to the app's purpose)

Good report

**Comment by bachletuankhai** [comment]
Purely cosmetic issue, not allowed to fix/change.
