### ISSUE TITLE
[Code quality/Functionality] isSamePerson method in Person subclasses violates LSP

### ISSUE THREAD

**Issue by bachletuankhai** [AY2324S2-CS2103T-F12-4/tp#140]
**Describe the bug**
`isSamePerson` in [Person.java:80-87](https://github.com/AY2324S2-CS2103T-F12-4/tp/blob/5eb62e076d382ec3900e0469ad5f9bccd1166d0e/src/main/java/seedu/address/model/person/Person.java#L80C5-L87C6) specifies that 2 Person are the same if they have the same name:
```java
public boolean isSamePerson(Person otherPerson) {
        if (otherPerson == this) {
            return true;
        }

        return otherPerson != null
                && otherPerson.getName().equals(getName());
}
```

However, the overriden `isSamePerson` method in Participant, Sponsor and Staff narrows down this specification. For example, in [Sponsor.java:56-66](https://github.com/AY2324S2-CS2103T-F12-4/tp/blob/5eb62e076d382ec3900e0469ad5f9bccd1166d0e/src/main/java/seedu/address/model/person/Sponsor.java#L56-L66):
```java
public boolean isSamePerson(Person other) {
     if (other == this) {
         return true;
     }

     if (!(other instanceof Sponsor)) {
         return false;
     }
     return super.isSamePerson(other);
}
```
A Sponsor is the same as other Person only if that Person is **also a Sponsor** and have **the same name**.
This is a violation of LSP. Also, if you want to modify `Person#isSamePerson` to enforce stricter condition on same person, it would lead to some scenarios where the same person can appear 3 times as different roles in the app.

**Potential solution**
Either:
1. Keep `isSamePerson` in `Person.java` and remove LSP-violating code in subclasses.
2. Move the current implementation of `Person#isSamePerson` to another `protected` method named `Person#isSamePersonBase`. Then make `Person#isSamePerson` abstract and change the call to `Person#isSamePerson` in subclasses to the new method.

**Comment by bachletuankhai** [comment]
@dhlee03 I think this is from your commit. I'm trying to implement a stricter duplicate person checker (person with same name and same phone number are the same), so the second approach would be preferred here. Let me know your opinion. No code is needed from you, I will fix this in my PR too.

**Comment by dhlee03** [comment]
@bachletuankhai Yes, I also think the second approach seems to be better.
