### ISSUE TITLE
Add UI indication when a row has a comment

### ISSUE THREAD

**Issue by bachletuankhai** [AY2324S2-CS2103T-F12-4/tp#51]
**Is your feature request related to a problem? Please describe.**
There is no visual cue for user to see if a contact has a comment or not.

**Describe the solution you'd like**
A visual cue (a dot or flag etc.) on the row with comment.

**Comment by bachletuankhai** [comment]
@dhlee03 can look into this? Or else we can just drop it when wrapping up v1.3

**Comment by dhlee03** [comment]
@bachletuankhai I dont think i can finish this in one hour

**Comment by bachletuankhai** [comment]
@dhlee03 we are allowed to delay the release until 10am tmr

**Comment by dhlee03** [comment]
Close it for now and I will try implementing it for v1.3.1

**Comment by dhlee03** [comment]
@bachletuankhai added the UI for the comment
