### ISSUE TITLE
[PE-D][Tester B] Unclear description of list command in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#76]
Example given in the description of list command is unclear. `Total: <total number of data>` is stated in the description, however no such command or output following the example is given.

![image.png](https://raw.githubusercontent.com/KohGuanZeh/ped/main/files/4dc24ced-86e0-4152-9ec6-553fb620852d.png)

![image.png](https://raw.githubusercontent.com/KohGuanZeh/ped/main/files/6cfe9c56-bbcb-4caa-ac0e-76b31254cbbc.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: KohGuanZeh/ped#5

**Comment by bachletuankhai** [comment]
- descriptive title: :heavy_check_mark:
- enough details: :heavy_check_mark: 
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :heavy_check_mark:

Good report
