### ISSUE TITLE
[PE-D][Tester C] Persons with same name are considered duplicate 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#79]
HackLink recognises two people as duplicates if the name is the same, even if the other contact informations are different. This may pose an issue as it is highly possible for participants to have the same name. 

For example, ap n/Davian p/84889861 e/davian@yahoo.com successfully creates a participant, but  ap n/Davian p/87654321 e/davian123@yahoo.com will fail to add as a different participant as he is recognised as an existing person. 

Perhaps, a person's name, phone number and email can be compared to determine if he is indeed a duplicate. 
![Screenshot 2024-04-05 at 4.27.34 PM.png](https://raw.githubusercontent.com/NatLeong/ped/main/files/681e64bf-f21b-4ea5-99a3-f98366babe2f.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: NatLeong/ped#2

**Comment by bachletuankhai** [comment]
- descriptive title: :heavy_check_mark:
- enough details: ✔️ 
- severity/type labels chosen are not too far off: :heavy_check_mark:
- non-confrontational tone: :heavy_check_mark:
- points out a potentially problematic behavior (or a good way to improve the product): :heavy_check_mark:

Good report

**Comment by bachletuankhai** [comment]
Should use person name and phone number to differentiate between people. It is possible that 1 person has 2 or more phone numbers, but 2 person cannot have the same phone number. This will be enough for allowing people with same name to be entered into the database, but preventing possible duplicate contacts.
