### ISSUE TITLE
[PE-D][Tester B] Edit function does not work as specified in the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-4/tp#81]
In the UG, the edit command is said to allow the editing of categories. However, when running the command, it throws an error message.

![image.png](https://raw.githubusercontent.com/KohGuanZeh/ped/main/files/d6fb5b9f-3332-4422-b0ad-bc8583390128.png)

![image.png](https://raw.githubusercontent.com/KohGuanZeh/ped/main/files/403a697b-0b35-4eaa-8e1a-521244ea48ea.png)

Steps to reproduce:
1. Ensure list is populated with at least 1 person that is a participant.
2. Run edit 1 c/staff
3. Error message shows

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: KohGuanZeh/ped#7

**Comment by dhlee03** [comment]
descriptive title: ✔️
enough details: ✔️
severity/type labels chosen are not too far off: ✔️
non-confrontational tone: ✔️
points out a potentially problematic behavior (or a good way to improve the product): ✔️
Good report

**Comment by dhlee03** [comment]
Fixed this issue by updating ug.
